module.exports = {
  extends: ["eslint:recommended", "prettier"],
  plugins: ["prettier"],
  rules: {
    "import/no-extraneous-dependencies": "warn",
    "import/order": [
      "warn",
      {
        "newlines-between": "always",
      },
    ],
    "no-case-declarations": "warn",
    "no-console": "error",
    "no-debugger": "warn",
    "no-else-return": "warn",
    "no-extra-semi": 2,
    "no-param-reassign": "warn",
    "no-undef": "off",
    "no-unneeded-ternary": "error",
    "no-unused-vars": ["error", { args: "none" }],
    "no-var": "warn",
    "object-shorthand": "warn",
    "prefer-const": "warn",
    "prefer-destructuring": ["warn", { object: true, array: true }],
    "prefer-template": "error",
    camelcase: "off",
    curly: "error",
    semi: [2, "always"],
  },
};
